FROM node:20-alpine AS pruner
WORKDIR /app
RUN corepack enable pnpm && npm i -g turbo
COPY . .
RUN turbo prune @bull-bear/web --docker

FROM node:20-alpine AS builder
WORKDIR /app
RUN corepack enable pnpm
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile
COPY --from=pruner /app/out/full/ .
RUN pnpm --filter @bull-bear/web build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./.next/static
COPY --from=builder /app/apps/web/public ./public
CMD ["node", "server.js"]
